-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 15:09:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gradebook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gradebook` ;

-- -----------------------------------------------------
-- Schema gradebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gradebook` DEFAULT CHARACTER SET utf8 ;
USE `gradebook` ;

-- -----------------------------------------------------
-- Table `gradebook`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gradebook`.`teacher` ;

CREATE TABLE IF NOT EXISTS `gradebook`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gradebook`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gradebook`.`classroom` ;

CREATE TABLE IF NOT EXISTS `gradebook`.`classroom` (
  `classroom_id` INT NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(45) NULL,
  `grade` VARCHAR(45) NULL,
  `teacher_id` INT NULL,
  PRIMARY KEY (`classroom_id`),
  INDEX `fk_classroom_teacher_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_classroom_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `gradebook`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
